FROM openjdk:8-jre

MAINTAINER finding findingwch@163.com

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

ARG JAR_FILE=./*.jar

COPY ${JAR_FILE} alipay-demo-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-Xmx256m", "-jar", "alipay-demo-0.0.1-SNAPSHOT.jar"]
CMD ["--spring.profiles.active=dev"]

EXPOSE 30001